#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi
# Redirect output to stderr.
exec 1>&2
echo -n "start pre-commit hook... "
# Rustの設定
for FILE in $(git status --short|grep '^[MA]'|cut -c4-|grep -E '.*\.rs'|grep -v 'vendor'); do
  rustfmt "$FILE"
  chmod 644 "$FILE"
  git add "$FILE"
done
for FILE in $(git status --short|grep '^[MA]'|cut -c4-|grep -E '.*\.sln'|grep -v 'vendor'); do
  sed -i -E '/Mixed Platform/d' "$FILE"
  git add "$FILE"
done
echo "done."
